--Task: Find categories whose total revenue is higher than the average revenue generated by all categories.
select category 
from (
    select p.category, sum(oi.quantity * p.price) as category_revenue
    from order_items oi 
        join products p
        on oi.product_id = p.product_id
        group by p.category ) category_sales
where category_revenue > (
    select avg(category_revenue)
    from (
        select p.category, sum(oi.quantity * p.price) as category_revenue
            from order_items oi
            join products p
            on oi.product_id = p.product_id
            group by p.category
    ) avg_sales
);