-- Task:
-- The company wants to analyze product performance
-- within each product category.
-- For each product, calculate:
-- - the total revenue generated by the product
-- - the product's rank within its category based on revenue
-- - the difference between the product's revenue and
--   the previous product's revenue in the category ranking
-- Return:
-- product_id,
-- product_name,
-- category,
-- product_revenue,
-- category_revenue_rank,
-- difference_from_previous_product

with products_metrics as
(
    select p.product_id,
    p.product_name,
    p.category,
    sum(p.price*oi.quantity) as product_revenue
    from products p
    join order_items oi
    on p.product_id = oi.product_id
    group by p.product_id,
    p.product_name,
    p.category
),
products_ranking as
(
    select pm.product_id,
    pm.product_name,
    pm.category,
    pm.product_revenue,
    rank() over (
        partition by pm.category
        order by pm.product_revenue desc
    ) as category_revenue_rank,
    lag(pm.product_revenue) over (
        partition by pm.category
        order by pm.product_revenue desc,
        pm.product_id
    ) as previous_product
    from products_metrics pm
)
select pr.product_id,
pr.product_name,
pr.category,
pr.product_revenue,
pr.category_revenue_rank,
(pr.product_revenue-pr.previous_product) as difference_from_previous_product  
from products_ranking pr
;
