--Task: Show total revenue generated by each product category.
select p.category, sum(oi.quantity*p.price) as total_revenue
from order_items oi
    join products p
    on oi.product_id = p.product_id
group by p.category
order by total_revenue desc;